title: Hello, world! I'm David Freeman
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
#baseurl: "https://webdevmarkup.github.io/" # the subpath of your site, e.g. /blog
url: "https://webdevmarkup.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: '0x3b' # add your name
author-img: js-1.png # add your photo
about-author: 블로그 설명 주저리주러리 # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: webDevMarkup # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address
#social-slack: 

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

# Disable Disk Cache
disable_disk_cache: BOOL
